const LIST_SEARCH_PARAM_KEY = 'keyword'
const LIST_PAGE_PARAM_KEY = 'page'
const LIST_PAGESIZE_PARAM_KEY = 'pageSize'
const LIST_PAGESIZE_LIMIT = 10
const STAT_COLORS = ['#FF2D2D', '#BE77FF', '#2894FF', '#00EC00', '#EAC100', '#FF9D6F']

export {
  LIST_SEARCH_PARAM_KEY,
  LIST_PAGE_PARAM_KEY,
  LIST_PAGESIZE_PARAM_KEY,
  LIST_PAGESIZE_LIMIT,
  STAT_COLORS,
}
