const LIST_SEARCH_PARAM_KEY = 'keyword'
const LIST_PAGE_PARAM_KEY = 'page'
const LIST_PAGESIZE_PARAM_KEY = 'pageSize'
const LIST_PAGESIZE_LIMIT = 10
export { LIST_SEARCH_PARAM_KEY, LIST_PAGE_PARAM_KEY, LIST_PAGESIZE_PARAM_KEY, LIST_PAGESIZE_LIMIT }
